'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),app=fs.readFileSync(path.join(root,'src/renderer/app.js'),'utf8');
function apply(source){let callbacks=[];const elements=new Map(),el=id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id);};const ctx={settings:{iconSize:72,theme:'matrix'},document:{documentElement:{style:{setProperty(){}}}},elSliderIconSize:{},elIconSizeVal:{},elChkStartup:{},elChkRandomTheme:{},$:el,applyReducedMotion(){},VALID_THEMES:new Set(['matrix']),startBannerCycle(){},window:{qlRadialRefresh:()=>callbacks.push('radial')},onSkinApplied:()=>callbacks.push('picker')};vm.runInNewContext(source+';applySettings();',ctx);return{callbacks,ctx};}
const applied=app.slice(app.indexOf('function applySettings() {'),app.indexOf('// Apply reduced-motion: union'));
test('actual merged theme application refreshes both radial geometry and skin selection marks',()=>{assert.deepEqual(apply(applied).callbacks,['radial','picker']);});
test('omitting either merged callback is a detected integration mutation',()=>{for(const line of ['if (window.qlRadialRefresh) window.qlRadialRefresh();','if (onSkinApplied) onSkinApplied();']){const bad=applied.replace(line,'');assert.notEqual(bad,applied);assert.throws(()=>assert.deepEqual(apply(bad).callbacks,['radial','picker']));}});
function escape(source){const listeners=[],calls=[],layer=()=>({classList:{hidden:false,contains(){return this.hidden;},add(){this.hidden=true;}}}),cheat=layer(),settings=layer(),picker=layer();const ctx={document:{addEventListener:(_type,fn)=>listeners.push(fn),getElementById:()=>cheat},elSettingsOverlay:settings,elAppsPicker:picker,_filterText:'a',editMode:true,closeCheatsheet:()=>{calls.push('cheat');cheat.classList.hidden=true;},closeSettings:()=>{calls.push('settings');settings.classList.hidden=true;},clearFilter:()=>{calls.push('filter');ctx._filterText='';},exitEditMode:()=>{calls.push('edit');ctx.editMode=false;}};vm.runInNewContext(source,ctx);const press=()=>listeners.forEach(fn=>fn({key:'Escape',target:{tagName:'BODY'},preventDefault(){}}));return{ctx,cheat,settings,picker,calls,press};}
const keyStart=app.indexOf("document.addEventListener('keydown', (e) => {");
const key=app.slice(keyStart,app.indexOf('\n});',keyStart)+4);
test('actual Escape ladder removes one layer per press and never also exits edit mode',()=>{const s=escape(key);s.press();assert.deepEqual(s.calls,['cheat']);assert.equal(s.ctx.editMode,true);s.press();assert.deepEqual(s.calls,['cheat','settings']);s.press();assert.equal(s.picker.classList.hidden,true);assert.equal(s.ctx._filterText,'a');s.press();assert.equal(s.ctx._filterText,'');assert.equal(s.ctx.editMode,true);s.press();assert.equal(s.ctx.editMode,false);s.press();assert.deepEqual(s.calls,['cheat','settings','filter','edit']);});
test('known-bad duplicate Escape handler wrongly exits edit mode under a cheat sheet',()=>{const s=escape(key+"\ndocument.addEventListener('keydown',e=>{if(e.key==='Escape'&&editMode)exitEditMode();});");s.press();assert.equal(s.ctx.editMode,false);assert.throws(()=>assert.equal(s.ctx.editMode,true));});
test('reachable Settings button still invokes scoped Manager rather than legacy overlay',()=>{const start=app.indexOf("$('btn-settings').addEventListener('click', () => {");const wire=app.slice(start,app.indexOf('\n});',start)+4);let click,calls=[];vm.runInNewContext(wire,{$:()=>({addEventListener:(_type,fn)=>click=fn}),window:{api:{invoke:(...args)=>calls.push(args)}}});click();assert.equal(calls[0][0],'region:open-manager');assert.equal(calls[0][1].view,'settings');});
test('both branches command registry survives and prebuild still gates contrast then hover',()=>{const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));for(const key of ['gallery:themes','gallery:regions','test:regions','selftest:regions','tryit:regions','check:contrast','check:hover','check'])assert.ok(pkg.scripts[key],key);assert.equal(pkg.scripts.prebuild,'npm run check');assert.equal(pkg.scripts.check,'npm run check:contrast && npm run check:hover');});
test('actual migration guard mutations lose malformed/oversized default reset',()=>{const source=fs.readFileSync(path.join(root,'src/main/regions/model.js'),'utf8'),ctx={workArea:{x:0,y:0,width:1920,height:1040},newId:()=> 'r1',defaultTheme:'cyberpunk',validThemes:new Set(['cyberpunk'])};for(const [bad,input]of [[source.replace('Number.isInteger(saved.width) && Number.isInteger(saved.height)','isFiniteNum(saved.width) && isFiniteNum(saved.height)'),{windowSize:{width:500.5,height:300.5}}],[source.replace('validSize && !oversized ? saved : null','validSize ? saved : null'),{windowSize:{width:1921,height:300}}]]){assert.notEqual(bad,source);const mod={exports:{}};vm.runInNewContext(bad,{module:mod,require:n=>require(path.join(root,'src/main/regions',n))});const result=mod.exports.migrate({apps:[],settings:input},ctx).data.regions[0].rect;assert.notEqual(result.width,424,'actual guard mutation breaks default width');assert.throws(()=>assert.equal(result.width,424));}});
