/* Display names for the theme pickers in the Manager window. A copy of
   THEME_NAMES in app.js (the region page); the two become one shared file in
   M6, after wip/theme-fidelity merges (tech plan § 1.5). A theme missing here
   shows its key in capitals. */
window.QL_THEME_NAMES = {
  'cyberpunk':           'CYBERPUNK',
  'blade-runner':        'BLADE RUNNER',
  'alien':               'ALIEN',
  'tron':                'TRON',
  'lcars':               'LCARS',
  'pip-boy':             'PIP-BOY',
  'dune':                'DUNE',
  'x-files':             'X-FILES',
  'mass-effect':         'MASS EFFECT',
  'deus-ex':             'DEUS EX',
  'ghost-shell':         'GHOST IN THE SHELL',
  'matrix':              'MATRIX',
  'warhammer':           'WARHAMMER 40K: IMPERIUM',
  'warhammer-chaos':     'WARHAMMER 40K: CHAOS',
  'warhammer-orks':      'WARHAMMER 40K: ORKS',
  'warhammer-eldar':     'WARHAMMER 40K: ELDAR',
  'warhammer-necrons':   'WARHAMMER 40K: NECRONS',
  'warhammer-tyranids':  'WARHAMMER 40K: TYRANIDS',
  'predator':            'PREDATOR',
  'robocop':             'ROBOCOP',
  'ff6':                 'FINAL FANTASY VI',
  'ff8':                 'FINAL FANTASY VIII',
  'ff9':                 'FINAL FANTASY IX',
  'ff10':                'FINAL FANTASY X',
  'ff14':                'FINAL FANTASY XIV',
  'ff15':                'FINAL FANTASY XV',
  'wow-horde':           'WOW: HORDE',
  'wow-scourge':         'WOW: SCOURGE',
  'wow-legion':          'WOW: BURNING LEGION',
  'wow-nightelf':        'WOW: NIGHT ELVES',
  'wow-alliance':        'WOW: ALLIANCE',
  'dead-space':          'DEAD SPACE',
  'half-life':           'HALF-LIFE',
  'terminator':          'TERMINATOR',
  'portal':              'PORTAL',
  'star-wars-rebel':     'STAR WARS: REBEL ALLIANCE',
  'star-wars-empire':    'STAR WARS: GALACTIC EMPIRE',
  'star-wars-mando':     'STAR WARS: MANDALORIAN',
  'star-wars-separatist': 'STAR WARS: SEPARATISTS',
  'star-wars-sith':      'STAR WARS: SITH',
  'star-wars-republic':  'STAR WARS: OLD REPUBLIC',
  'doctor-who':          'DOCTOR WHO',
  'akira':               'AKIRA',
  'evangelion':          'EVANGELION',
  '2001':                '2001: A SPACE ODYSSEY',
  'silent-hill':         'SILENT HILL',
  'stalker':             'S.T.A.L.K.E.R.',
  'resident-evil':       'RESIDENT EVIL',
  'the-expanse':         'THE EXPANSE',
  'event-horizon':       'EVENT HORIZON',
  'hogwarts':            'HOGWARTS: MARAUDER\'S MAP',
  'ministry-of-magic':   'MINISTRY OF MAGIC',
  'gryffindor':          'GRYFFINDOR',
  'ravenclaw':           'RAVENCLAW',
  'hufflepuff':          'HUFFLEPUFF',
  'slytherin':           'SLYTHERIN: DARK ARTS',
  'rivendell':           'RIVENDELL',
  'shire':               'THE SHIRE',
  'mordor':              'MORDOR',
  'scp':                 'SCP FOUNDATION',
  'alan-wake':           'ALAN WAKE',
  'control':             'CONTROL: THE BUREAU',
  'twin-peaks':          'TWIN PEAKS',
  'lovecraft':           'LOVECRAFTIAN',
  'the-sandman':         'THE SANDMAN',
  'persona-5':           'PERSONA 5',
  'the-witcher':         'THE WITCHER',
  'diablo':              'DIABLO',
  'soma':                'SOMA',
  'stranger-things':     'STRANGER THINGS',
  'fatal-frame':         'FATAL FRAME',
  'firefly':             'FIREFLY / SERENITY',
  'persona-4':           'PERSONA 4',
  'persona-3':           'PERSONA 3',
  'eve-online':          'EVE ONLINE',
  'indiana-jones':       'INDIANA JONES',
  'game-of-thrones':     'GAME OF THRONES',
  'doom-classic':        'DOOM (CLASSIC)',
  'doom-eternal':        'DOOM ETERNAL',
  'tiny-bunny':          'ЗАЙЧИК / TINY BUNNY',
  'promise-mascot':      'PROMISE MASCOT AGENCY',
  'mortal-kombat':       'MORTAL KOMBAT',
  'nonary-games':        'NONARY GAMES / ZERO ESCAPE',
  'life-is-strange':     'LIFE IS STRANGE',
  'dragon-age':          'DRAGON AGE',
  'yakuza':              'YAKUZA / LIKE A DRAGON',
  'mirrors-edge':        'MIRROR\'S EDGE',
  'tomb-raider':         'TOMB RAIDER',
  'uncharted':           'UNCHARTED',
  'broken-sword':        'BROKEN SWORD',
  'swl-illuminati':      'SWL: ILLUMINATI',
  'swl-templar':         'SWL: TEMPLAR',
  'swl-dragon':          'SWL: DRAGON',
  'ac-assassins':        'AC: ASSASSINS',
  'ac-templars':         'AC: TEMPLARS',
  'siren':               'FORBIDDEN SIREN',
  'blair-witch':         'BLAIR WITCH',
  'amnesia':             'AMNESIA',
  'metal-gear':          'METAL GEAR SOLID',
  'parasite-eve':        'PARASITE EVE',
  'ff7':                 'FINAL FANTASY VII',
};
